version: "3"
services:

  metadata:
    build: .
    restart: always
    volumes:
      - ./app:/app
    logging:
      driver: "json-file"
      options:
          max-size: "2m"
          max-file: "10"
    environment:
      - USE_SOCK_FILE=True
      - MONGO_CONNECTION_STRING=mongodb://root:root@mongo:27017
